### PR TITLE
Authorship based on blame

### LINKED ISSUE #234: Implement Dominant Authors metric based on git-blame
In case Thomas finishes earlier than expected with the multi-branch analysis... I think this would be awesome to have :)

Surely, I'm saying Thomas because he seemed more dedicated to the parser, but I might be wrong here!

Also, if this is a duplication, then feel free to close it.

### PR DESCRIPTION
**Pull request by emiljapelt**
Fixes #234

### CODE REVIEW

File: src/metrics.ts [hunk 1]
```diff
@@ -72,8 +78,28 @@ export interface MetricCache {
   colormap: Map<string, string>
 }
 
+// export interface authorColorState {
+//   palette: chroma.Color[]
+//   paletteIndex: number
+//   cache: Map<string, string>
+// }
```
Comment (joglr) [inline src/metrics.ts:85]: This should be removed, right?

**Review by joglr — CHANGES_REQUESTED** [review]
I think it works, but as a user, I am very confused what it means when selecting "Newest version".

The legend text should also change depending on which Authorship Data is selected
image

**Review by joglr — APPROVED** [review]
