### PR TITLE
Fix top contributor not shown for changes with 0 contributions

### LINKED ISSUE #699: Top contributor not shown
image

### PR DESCRIPTION
**Pull request by tjomson**
Fixes #699

### CODE REVIEW

File: src/metrics/topContributer.ts [hunk 1]
```diff
@@ -10,17 +10,16 @@ export function setDominantAuthorColor(
...
-    sorted = Object.entries(authorUnion).sort(([k1, v1], [k2, v2]) => {
-      if (v1 === 0 || v2 === 0 || !k1 || !k2) throw Error
-      if (v1 < v2) return 1
-      else if (v1 > v2) return -1
-      else return 0
-    })
-    if (!sorted[0]) throw Error
-  } catch {
+  if (!authorUnion) {
+    console.log("No author union found for file", blob.path)
```
Comment (joglr) [inline src/metrics/topContributer.ts:14]: Would this make sense as a warning instead? 


```suggestion
    console.warn("No author union found for file", blob.path)
```

File: src/metrics/topContributer.ts [hunk 2]
```diff
@@ -10,17 +10,16 @@ export function setDominantAuthorColor(
...
+    return
+  }
+  const sorted = Object.entries(authorUnion).sort(([k1, v1], [k2, v2]) => {
+    if (v1 === 0 || v2 === 0 || !k1 || !k2) return -1
+    return v2 - v1
+  })
+  if (!sorted[0]) {
+    console.log("No sorted authors for file", blob.path)
```
Comment (joglr) [inline src/metrics/topContributer.ts:22]: Would this make sense as a warning instead? 


```suggestion
    console.warn("No sorted authors for file", blob.path)
```

**Review by joglr — APPROVED** [review]
