### PR TITLE
Fix special characters

### LINKED ISSUE #343: Special characters are shown as codes
cat-file and diff can't handle special characters

billede

fx. å, ø, β

### PR DESCRIPTION
**Pull request by tjomson**
resolves #343 

now disables quotepath before parsing, and afterwards resets it back to what it was

### CODE REVIEW

File: src/parser/util.ts [hunk 1]
```diff
@@ -114,6 +114,28 @@ export async function deflateGitObject(repo: string, hash: string) {
...
+  return result as string
+}
+
+export async function disableQuotePath(repoDir: string) {
+  await runProcess(repoDir, "git", ["config", "core.quotepath", "off"])
+  log.debug("Disabled quotePath")
+}
+
+export async function resetQuotePath(repoDir: string, value: string) {
+  log.debug("value: " +  value)
```
Comment (joglr) [inline src/parser/util.ts:128]: Could this log be a bit more clear on what is logged?

Comment (tjomson) [reply src/parser/util.ts:128]: Oh, that should have been deleted, thanks for catching :D

**Review by emiljapelt — APPROVED** [review]
Works, ver nice :rock:
