### PR TITLE
Turn project into installable CLI

### LINKED ISSUE #255: Incorrect outPath from CLI
image

The default output location should be .temp in git-visual.

### LINKED ISSUE #262: Open browser automatically when running `start`

### LINKED ISSUE #287: Call parser from remix loader
Currently, the data is read from the file system, after the parser has been run manually

- [x] Move parser into app
- [x] Take args from `process.args` in index.tsx `LoaderFunction` and call parser
- [x] Call parser with args from the `LoaderFunction`
- [x] Evaluate how the logging works when parser is run via remix

### LINKED ISSUE #288: Setup project as an NPM package
In `package.json`, these fields should be updated in order to run the tool.

- [x] Change `name` to `git-truck`
- [x] Change `private` to false
- [x] Add `description`
- [x] Add version
- [x] Set license
- [x] Use express remix deployment
- [x] Set "bin" to express entry point

### LINKED ISSUE #312: Enable setting log level as an argument

### LINKED ISSUE #328: Update CI workflow to test specific node versions
Using matrix

### LINKED ISSUE #332: Remove deployment step from workflow for now

### PR DESCRIPTION
**Pull request by joglr**
This fuses the parser and visualization into a single project.

- [x] Fixes #287
- [x] Fixes #332 
- [x] Fixes #328 
- [x] Fixes #288 
- [x] Fixes #255 
- [x] Fixes #312
- [x] Fixes #262
- [ ] Update usage instructions

A lot of the changes are renamings.
A lot of config files are deleted, since most of it is handled by remix and most of it is duplicated across visualization and parser.

Some parser files are renamed to *.server glob, because Remix uses the name to determine if it is a client side file or a server side file. See https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles

### CODE REVIEW

File: app/parser/src/TruckIgnore.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { readFileSync } from "fs"
 import { compile } from "gitignore-parser"
-import { warn } from "./log"
+import { warn } from "./log.server"
```
Comment (joglr) [inline app/parser/src/TruckIgnore.ts:3]: Remix uses the *.server glob to determine if it is a clientside file or a server side file

See https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles

File: app/parser/src/index.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 import "dotenv/config"
-import { parse } from "./parse"
+import { parse } from "./parse.server"
```
Comment (tjomson) [inline app/parser/src/index.ts:2]: Is calling it parse.server just some convention?

File: app/parser/src/log.server.ts [hunk 3]
```diff
@@ -24,14 +23,24 @@ const stringToLevelMap: Record<string, LOG_LEVEL> = {
...
 }
 
-const logLevel = getLogLevel()
+let logLevel = setIntialLogLevel()
+
+export const getLogLevel = () => logLevel
+
+export function setLogLevel(level: string) {
+  const newLevel = stringToLevelMap[level.trim().toUpperCase()]
+  if(typeof newLevel === "undefined") {
```
Comment (tjomson) [inline app/parser/src/log.server.ts:39]: Is this check different from *!newLevel*?

File: app/parser/src/parse.server.ts [hunk 4]
```diff
@@ -239,26 +245,30 @@ export async function parse(rawArgs: string[]) {
...
+  }
   await describeAsyncJob(
     () =>
-      writeRepoToFile(outPath, {
-        repo: repoName,
-        branch: branchName,
-        commit: hydratedRepoTree,
-        authorUnions: authorUnions,
-      }),
+      writeRepoToFile(outPath, data),
```
Comment (tjomson) [inline app/parser/src/parse.server.ts:262]: Should we both write data to a file and return it? Is the written file mostly for debugging purposes?

File: app/routes/index.tsx [hunk 5]
```diff
@@ -1,11 +1,14 @@
...
-import App from "~/src/App";
-import fs from "fs"
-import { ParserData } from "parser/src/model";
+import { ParserData } from "~/parser/src/model";
 import appStyles from "~/styles/App.css"
 import varsStyles from "~/styles/vars.css"
 import indexStyles from "~/styles/index.css"
 import chartStyles from "~/styles/Chart.css"
+import { parse } from "~/parser/src/parse.server";
+import { Providers } from "~/src/components/Providers";
```
Comment (tjomson) [inline app/routes/index.tsx:8]: Should we maybe start using export default for components to make the imports cleaner?

File: app/src/metrics.ts [hunk 6]
```diff
@@ -58,12 +58,12 @@ export function getMetricCalcs(
   metricType: MetricType,
   func: (blob: HydratedGitBlobObject, cache: MetricCache) => void
 ][] {
-  let heatmap = new HeatMapTranslater(commit.minNoCommits, commit.maxNoCommits)
-  let coldmap = new ColdMapTranslater(
+  const heatmap = new HeatMapTranslater(commit.minNoCommits, commit.maxNoCommits)
```
Comment (tjomson) [inline app/src/metrics.ts:61]: Nice const's 😎

File: package.json [hunk 7]
```diff
@@ -1,51 +1,105 @@
...
-    "poststart": "npx cross-env NODE_ENV=production remix-serve build",
-    "clean": "npx rimraf -rf ./parser/dist data.json build",
-    "parse": "npm --prefix ./parser/ install && npm --prefix ./parser/ run build && npm --prefix ./parser/ start -- --gittruckroot .. --path . --out ./data.json"
+    "test": "jest --coverage",
+    "clean": "npx rimraf -rf ./parser/dist build public/build",
+    "build": "remix setup node && cross-env NODE_ENV=production remix build && node ./post-build.js",
+    "dev": "cross-env NODE_ENV=development remix build && run-p dev:*",
+    "dev:remix": "cross-env NODE_ENV=development remix watch",
+    "dev:node": "cross-env NODE_ENV=development nodemon ./build/index.js --watch ./build/index.js",
+    "start": "cross-env NODE_ENV=production node ./build/index.js"
```
Comment (tjomson) [inline package.json:16]: Is it possible to have a command for just running the parser, or just running the app?

**Review by tjomson — COMMENTED** [review]
Is the file structure what we want it to be?
Would it be better to have something like

                      root
                         |
                       src
                     /      \
                app      parser

I think if we do this, it is more clean than having an app folder, which contains src and parser, and then parser also contains an src

**Comment by joglr** [comment]
> Is the file structure what we want it to be? Would it be better to have something like
> 
> ```
>                   root
>                      |
>                    src
>                  /      \
>             app      parser
> ```
> 
> I think if we do this, it is more clean than having an app folder, which contains src and parser, and then parser also contains an src

Yes, it makes great sense to think about the structure when we are moving so many things aroung anyways.

File: .husky/.gitignore [hunk 8]
```diff
@@ -0,0 +1 @@
+_
```
[the remark this answers is not in the document]
Comment (joglr) [reply .husky/.gitignore:1]: Husky generates it to ignore scripts produced when husky is installed.

File: app/parser/src/log.server.ts (hunk 3 above)
Comment (joglr) [reply app/parser/src/log.server.ts:39]: Yes, since silent is 0 in the `LOG_LEVEL` enum, it would prouce a falsy value when casted to a boolean and therefore, you were unable to set log level to SILENT.

File: app/routes/index.tsx (hunk 5 above)
Comment (joglr) [reply app/routes/index.tsx:8]: Idk, I kinda like named exports, since it enforces you to import the exported value as the name it was defined as.

File: package.json (hunk 7 above)
Comment (joglr) [reply package.json:16]: Yeah, that makes sense, but I would think it is out of scope of this monster PR, no?

File: .github/workflows/test-and-build.yml [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+  pull_request:
+    branches: [main]
+
+jobs:
+  test-and-build:
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        node-version: [16.x, 17.x]
```
[the remark this answers is not in the document]
Comment (joglr) [reply .github/workflows/test-and-build.yml:18]: That would be nice, but it requires that we change this dependency: 
    "github-colors": "git+https://github.com/ozh/github-colors.git",
Since it breaks in Node 14.

File: app/parser/src/parse.server.ts (hunk 4 above)
Comment (tjomson) [reply app/parser/src/parse.server.ts]: For debugging and chaching later on

File: README.md [hunk 10]
```diff
@@ -14,37 +14,60 @@ This projected is tested to work with:
...
 ## [Usage](#usage)
 
-1. Install dependencies with `npm install`
-2. Build the project with `npm run build`
-3. Then run the app in production mode:
+Run the tool like this:
 
 ```sh
-npm start -- [--path <path>] [--branch <name>] [--out <path>]
+npx git-truck [--path <path>] [--branch <name>] [--out <path>] [--log <path>]
```
[the remark this answers is not in the document]
Comment (tjomson) [reply README.md:20]: Still not working, but will be fixed later

**Review by hojelse — APPROVED** [review]
Gogogo :t-rex:

**Review by tjomson — APPROVED** [review]
🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀
